### ISSUE TITLE
Exercice 2 : Update team member information

### ISSUE THREAD

**Issue by dhmmasson** [Estia-advanced-programming/pandora-template#3]
# Description 

In this exercice all member will edit the same file on their local repository to learn about conflict resolution. 

# Task

- [ ] Member1 modify `README.md` and create a commit locally
- [ ] Member2 modify `README.md` and create a commit locally
- [ ] Member3 modify `README.md` and create a commit locally
- [ ] Member1 *push* their commit to the remote repository
- [ ] Member2 and 3 
          - Pull the commit from member1
          - Merge the modification into their local repository
          - Commit 
- [ ] Member2  *push* their commit to the remote repository
- [ ] Member2 and 3 
          - Pull the commit from member1
          - Merge the modification into their local repository
          - Commit
